trigger:
- main

pool:
  name: Default
  demands:
    - agent.name -equals LE-KIEN

variables:
  buildConfiguration: Release
  api_publish: '$(Build.ArtifactStagingDirectory)/api'
  mvc_publish: '$(Build.ArtifactStagingDirectory)/mvc'

steps:

# ===============================
# 0. CLEAN ARTIFACT FOLDER
# ===============================
- powershell: |
    Write-Host "Cleaning old artifact folder"
    Remove-Item "$(Build.ArtifactStagingDirectory)" -Recurse -Force -ErrorAction SilentlyContinue
  displayName: Clean artifact folder


# ===============================
# 1. RESTORE
# ===============================
- task: DotNetCoreCLI@2
  displayName: Restore
  inputs:
    command: restore
    projects: '**/*.csproj'


# ===============================
# 2. BUILD
# ===============================
- task: DotNetCoreCLI@2
  displayName: Build
  inputs:
    command: build
    projects: '**/*.csproj'
    arguments: '--configuration $(buildConfiguration)'


# ===============================
# 3. PUBLISH API (NO FOLDER)
# ===============================
- task: PowerShell@2
  displayName: Publish API
  inputs:
    targetType: inline
    script: |
      Write-Host "Publishing API (dotnet publish)..."
      dotnet publish "Warehouse.API/Warehouse.API.csproj" `
        -c Release `
        -o "$(api_publish)"


# ===============================
# 4. PUBLISH MVC (NO FOLDER)
# ===============================
- task: PowerShell@2
  displayName: Publish MVC
  inputs:
    targetType: inline
    script: |
      Write-Host "Publishing MVC (dotnet publish)..."
      dotnet publish "Warehouse.MVC/Warehouse.MVC.csproj" `
        -c Release `
        -o "$(mvc_publish)"


# ===============================
# 5. DEPLOY API
# ===============================
- task: PowerShell@2
  displayName: Deploy API to IIS
  inputs:
    targetType: inline
    script: |
      Write-Host "Cleaning API folder"
      Remove-Item "C:\inetpub\WarehouseAPI" -Recurse -Force -ErrorAction SilentlyContinue
      New-Item -ItemType Directory -Path "C:\inetpub\WarehouseAPI" | Out-Null

      Write-Host "Copy API files"
      robocopy "$(api_publish)" "C:\inetpub\WarehouseAPI" /MIR

      Write-Host "API deployed successfully!"


# ===============================
# 6. DEPLOY MVC
# ===============================
- task: PowerShell@2
  displayName: Deploy MVC to IIS
  inputs:
    targetType: inline
    script: |
      Write-Host "Cleaning MVC folder"
      Remove-Item "C:\inetpub\WarehouseMVC" -Recurse -Force -ErrorAction SilentlyContinue
      New-Item -ItemType Directory -Path "C:\inetpub\WarehouseMVC" | Out-Null

      Write-Host "Copy MVC files"
      robocopy "$(mvc_publish)" "C:\inetpub\WarehouseMVC" /MIR

      Write-Host "MVC deployed successfully!"
